from rest_framework import serializers

class TripInputSerializer(serializers.Serializer):
    current_location = serializers.CharField(max_length=255, required=True)
    pickup_location = serializers.CharField(max_length=255, required=True)
    dropoff_location = serializers.CharField(max_length=255, required=True)
    cycle_hours_used = serializers.FloatField(
        min_value=0.0, 
        max_value=70.0, 
        required=False, 
        default=0.0
    )
    trailer_id = serializers.CharField(max_length=100, required=False, allow_blank=True)
    commodity = serializers.CharField(max_length=255, required=False, allow_blank=True)
    departure_time = serializers.DateTimeField(required=False, allow_null=True)

class TripPlanSerializer(serializers.Serializer):
    """
    Serializes the final response dictionary generated by LogSheetBuilder.
    Since the dictionary is already in the correct JSON-serializable format,
    we can use a DictField or pass the response directly in the view.
    """
    summary = serializers.DictField()
    route = serializers.DictField()
    days = serializers.ListField(child=serializers.DictField())
