import { jsPDF } from 'jspdf';

export const exportELDLogPDF = (dayData, canvas) => {
  if (!canvas || !dayData) return;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'letter'
  });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(28, 28, 23);
  doc.text(`Driver's Daily Log - Day ${dayData.day_number}`, 15, 20);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(114, 119, 130);
  doc.text(`Generated by SpotterAI ELD Trip Planner | Vehicle ID: CMV-7092`, 15, 26);

  const imgWidth = 186;
  const imgHeight = imgWidth * 0.3255;
  const imgData = canvas.toDataURL('image/png');
  doc.addImage(imgData, 'PNG', 15, 32, imgWidth, imgHeight);

  doc.setDrawColor(220, 224, 230);
  doc.setLineWidth(0.4);
  doc.line(15, 100, 201, 100);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(28, 28, 23);
  doc.text('Duty Status Recap', 15, 108);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(114, 119, 130);
  doc.text('STATUS CATEGORY', 15, 116);
  doc.text('TOTAL HOURS', 95, 116);
  doc.text('COMPLIANCE STATUS', 155, 116);

  doc.setDrawColor(240, 242, 245);
  doc.line(15, 119, 201, 119);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(28, 28, 23);
  const statuses = [
    { label: '1. Off Duty', val: dayData.totals?.off_duty },
    { label: '2. Sleeper Berth', val: dayData.totals?.sleeper_berth },
    { label: '3. Driving', val: dayData.totals?.driving },
    { label: '4. On Duty (Not Driving)', val: dayData.totals?.on_duty_nd }
  ];

  let y = 126;
  statuses.forEach((s) => {
    doc.text(s.label, 15, y);
    doc.text(`${(s.val || 0).toFixed(1)} hr`, 95, y);
    doc.text('Compliant', 155, y);
    doc.line(15, y + 3, 201, y + 3);
    y += 8;
  });

  doc.setFont('helvetica', 'bold');
  doc.text(`Total Working Time (Driving + On Duty): ${(dayData.totals?.total_working || 0).toFixed(1)} hr`, 15, y + 4);

  y += 16;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(28, 28, 23);
  doc.text('Remarks & Location Events', 15, y);
  doc.line(15, y + 4, 201, y + 4);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(114, 119, 130);
  doc.text('EVENT TIME', 15, y + 10);
  doc.text('LOCATION & ACTIVITY DESCRIPTION', 55, y + 10);
  doc.line(15, y + 12, 201, y + 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(28, 28, 23);
  y += 18;

  const remarks = dayData.remarks || [];
  remarks.forEach((rem) => {
    if (y > 265) {
      doc.addPage();
      y = 20;
    }
    doc.text(rem.time_label || '', 15, y);
    const desc = `${rem.location} - ${rem.activity}`;
    const splitDesc = doc.splitTextToSize(desc, 140);
    doc.text(splitDesc, 55, y);
    y += 6 * splitDesc.length + 2;
  });

  doc.save(`ELD_Log_Day_${dayData.day_number}.pdf`);
};
